name: Node.js CI on Self-Hosted Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Restart on EC2
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js (via nvm)
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm install 23
          nvm use 23
          node -v
          npm -v

      - name: Install dependencies
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 23
          npm ci

      - name: Run background script
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 23
          nohup ./run.sh > /actions-runner/runner.log 2>&1 & # Run in the background

      - name: Build (optional)
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 23
          npm run build || echo "No build script found"

      - name: Restart PM2
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 23
          pm2 restart 0 || pm2 start npm --name "my-app" -- start
