name: Node.js CI on Self-Hosted Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test on EC2
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x] # Only use versions installed on EC2 runner
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Restart PM2 (or your process manager)
        run: |
          pm2 restart 0 || pm2 start npm --name "my-app" -- start
